version: "3"
services: 
  react-app:
    # stdin_open: true #//for options -i
    # tty: true #//for optiond -t
    build:
      context: .
      dockerfile: Dockerfile.dev    
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      - REACT_APP_NAME=mithra
      - CHOKIDAR_USEPOLLING=true
    # env_file:
    #   - ./.env

