version: "3"
services: 
  react-app:
    # stdin_open: true #//for options -i
    # tty: true #//for optiond -t
    image: node:12.4.0
    build:
      constext: .
      dockerfile: Dockerfile    
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      - Name=mithra
      - CHOKIDAR_USEPOLLING=true
    # env_file:
    #   - ./.env

